[package]
name = "hello_axum"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
axum = "0.8.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
sqlx = { version = "0.8.3", features = ["mysql", "migrate", "chrono", "runtime-tokio"] }
tokio = { version = "1.43.1", features = ["full", "macros", "rt-multi-thread"] }
